/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as LiveChatsRouteImport } from './routes/live-chats'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConversationsConversationIdRouteImport } from './routes/conversations.$conversationId'
import { Route as EscalationsCaseIdRouteImport } from './routes/escalations.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveChatsRoute = LiveChatsRouteImport.update({
  id: '/live-chats',
  path: '/live-chats',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsConversationIdRoute =
  ConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => ConversationsRoute,
  } as any)
const EscalationsCaseIdRoute = EscalationsCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => EscalationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/errors': typeof ErrorsRoute
  '/escalations': typeof EscalationsRouteWithChildren
  '/ingestion': typeof IngestionRoute
  '/live-chats': typeof LiveChatsRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/escalations/$caseId': typeof EscalationsCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/errors': typeof ErrorsRoute
  '/escalations': typeof EscalationsRouteWithChildren
  '/ingestion': typeof IngestionRoute
  '/live-chats': typeof LiveChatsRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/escalations/$caseId': typeof EscalationsCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/errors': typeof ErrorsRoute
  '/escalations': typeof EscalationsRouteWithChildren
  '/ingestion': typeof IngestionRoute
  '/live-chats': typeof LiveChatsRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/escalations/$caseId': typeof EscalationsCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/conversations'
    | '/documents'
    | '/errors'
    | '/escalations'
    | '/ingestion'
    | '/live-chats'
    | '/overview'
    | '/settings'
    | '/conversations/$conversationId'
    | '/escalations/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/conversations'
    | '/documents'
    | '/errors'
    | '/escalations'
    | '/ingestion'
    | '/live-chats'
    | '/overview'
    | '/settings'
    | '/conversations/$conversationId'
    | '/escalations/$caseId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/conversations'
    | '/documents'
    | '/errors'
    | '/escalations'
    | '/ingestion'
    | '/live-chats'
    | '/overview'
    | '/settings'
    | '/conversations/$conversationId'
    | '/escalations/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  ErrorsRoute: typeof ErrorsRoute
  EscalationsRoute: typeof EscalationsRouteWithChildren
  IngestionRoute: typeof IngestionRoute
  LiveChatsRoute: typeof LiveChatsRoute
  OverviewRoute: typeof OverviewRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-chats': {
      id: '/live-chats'
      path: '/live-chats'
      fullPath: '/live-chats'
      preLoaderRoute: typeof LiveChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$conversationId': {
      id: '/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof ConversationsConversationIdRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/escalations/$caseId': {
      id: '/escalations/$caseId'
      path: '/$caseId'
      fullPath: '/escalations/$caseId'
      preLoaderRoute: typeof EscalationsCaseIdRouteImport
      parentRoute: typeof EscalationsRoute
    }
  }
}

interface ConversationsRouteChildren {
  ConversationsConversationIdRoute: typeof ConversationsConversationIdRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsConversationIdRoute: ConversationsConversationIdRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

interface EscalationsRouteChildren {
  EscalationsCaseIdRoute: typeof EscalationsCaseIdRoute
}

const EscalationsRouteChildren: EscalationsRouteChildren = {
  EscalationsCaseIdRoute: EscalationsCaseIdRoute,
}

const EscalationsRouteWithChildren = EscalationsRoute._addFileChildren(
  EscalationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  ErrorsRoute: ErrorsRoute,
  EscalationsRoute: EscalationsRouteWithChildren,
  IngestionRoute: IngestionRoute,
  LiveChatsRoute: LiveChatsRoute,
  OverviewRoute: OverviewRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
